<?php

function dump( $value )
{
    echo "<pre>";
    var_dump( $value );
    echo "</pre>";
}

/**
 * Gets a specific value from the .env file based on key. E.g. env('DB_HOST'); returns 127.0.0.1
 *
 * This function is generated by Windsurf.
 *
 * @param string $key
 * @param string $default
 */
function env( string $key, $default = null )
{
    global $dotenv;

    // Load .env file only once
    if ( $dotenv === null ) {
        $dotenv = [];
        $envFile = __DIR__ . '/../.env';

        // Check if .env file exists
        if ( !file_exists( $envFile ) ) {
            return $default; // Return default if file doesn't exist
        }

        $lines = file( $envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES );

        foreach ( $lines as $line ) {
            // Skip comments and empty lines
            $line = trim( $line );
            if ( $line === '' || str_starts_with( $line, '#' ) ) {
                continue;
            }

            // Split on the first '=' only
            if ( strpos( $line, '=' ) !== false ) {
                list( $envKey, $envValue ) = explode( '=', $line, 2 );
                $dotenv[trim( $envKey )] = trim( $envValue );
            }
        }
    }

    // Return the value for the requested key or the default
    return $dotenv[$key] ?? $default;
}
