<?php

function dump($value) {
    echo "<pre>";
        var_dump($value);
    echo "<pre>";
}

/**
 * Gets a specific value from the .env file based on key. E.g. env('DB_HOST'); returns 127.0.0.1
 * 
 * This function is generated by Windsurf.
 * 
 * @param string $key
 * @param string $default
 */
function env(string $key, string $default = null)
{
    $dotenv = [];
    $lines = file('.env', FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($lines as $line) {
        list($key, $value) = explode('=', $line, 2);
        $key = trim($key);
        $value = trim($value);
        if (strpos($key, '__') !== false) {
            $parts = explode('__', $key);
            $current = &$dotenv;
            foreach ($parts as $part) {
                if (!isset($current[$part])) {
                    $current[$part] = [];
                }
                $current = &$current[$part];
            }
            $current = $value;
        } else {
            $dotenv[$key] = $value;
        }
    }
    return $dotenv[$key] ?? $default;
}